cmake_minimum_required(VERSION 3.31)
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Build configuration")
set(CMAKE_PROJECT_TOP_LEVEL_INCLUDES .devcontainer/cmake/xproinc.cmake)
project(cmake-pkg VERSION 3.31.6 LANGUAGES CXX)
# https://github.com/Kitware/CMake/releases/tag/v3.31.6
# https://github.com/Kitware/CMake/releases/download/v3.31.6/cmake-3.31.6-linux-x86_64.tar.gz
# https://github.com/Kitware/CMake/releases/download/v3.31.6/cmake-3.31.6-linux-aarch64.tar.gz
set(sha_aarch64 b4cc788d63112b2749b40627e719eb5d3b8ed8f00c36d77189f4019cfe64bc9e)
set(sha_x86_64 5a1133ff103c71eb5120e2cc3de922733e7d8a26a98ae716397e8676adb367bf)
set(REPO https://github.com/Kitware/CMake)
string(TOLOWER ${CMAKE_SYSTEM_NAME} os)
if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64|AMD64)$")
  set(arch "x86_64")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)$")
  set(arch "aarch64")
endif()
set(url ${REPO}/releases/download/v${PROJECT_VERSION}/cmake-${PROJECT_VERSION}-${os}-${arch}.tar.gz)
set(opt DOWNLOAD_EXTRACT_TIMESTAMP true)
include(FetchContent)
FetchContent_Declare(cmake ${opt} URL ${url} URL_HASH SHA256=${sha_${arch}})
FetchContent_MakeAvailable(cmake)
install(DIRECTORY ${cmake_SOURCE_DIR}/ DESTINATION . USE_SOURCE_PERMISSIONS)
set(CPACK_GENERATOR RPM)
set(CPACK_RPM_PACKAGE_ARCHITECTURE ${arch})
# https://github.com/externpro/externpro/issues/53
set(CPACK_RPM_SPEC_MORE_DEFINE "%define _build_id_links none")
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr/local")
set(CPACK_PACKAGE_VERSION v${PROJECT_VERSION})
set(CPACK_SYSTEM_NAME ${os}-${arch})
include(CPack)
