name: xpBuild
permissions:
  contents: read
  pull-requests: write
on:
  push:
    tags: ["xpv*"]
  pull_request:
    branches: ["xpro"]
  workflow_dispatch:
jobs:
  linux:
    permissions:
      contents: read
      pull-requests: write
      packages: write
    uses: externpro/externpro/.github/workflows/build-linux.yml@25.07.10
    with:
      artifact-pattern: '${{ github.event.repository.name }}-*.rpm'
      cmake-workflow-preset: LinuxRelease
      buildpro-images: '["rocky9-gcc13"]'
    secrets:
      automation_token: ${{ secrets.GHCR_TOKEN }}
