name: xpBuild
permissions:
  contents: read
  pull-requests: write
on:
  push:
    tags: ["xpv*"]
  pull_request:
    branches: ["xpro"]
  workflow_dispatch:
jobs:
  linux:
    with:
      cmake-workflow-preset: LinuxRelease
      buildpro-images: ["rocky9-gcc13"]
      artifact-pattern: ${{ github.event.repository.name }}-*.rpm
    permissions:
      contents: read
      pull-requests: write
      packages: write
    uses: externpro/externpro/.github/workflows/build-linux.yml@main
    secrets:
      automation_token: ${{ secrets.GHCR_TOKEN }}
herit
